version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - python3-poetry

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false

python:
  install:
    - method: pip
      install_poetry: true
      path: .
      poetry_install_args: "--only docs"
