version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install uv
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false
