version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
