version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install poetry
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false
